name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build Docker image
        run: echo "OK"

      - name: Check if build was successful
        id: build_status
        run: echo "::set-output name=status::success"

  deploy:
    needs: build
    runs-on: [self-hosted, dev_node]
    if: github.ref == 'refs/heads/main' && needs.build.outputs.status == 'success'

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Deploy using Docker
        run: node -v
