on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo 'building'
          echo "KEY1=${{secrets.SC_KEY_1}}" >> .env
          echo "KEY2=${{secrets.SC_KEY_2}}" >> .env
          ls
          cat .env
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: publish
        run: echo 'publishing'
