on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'building'
      - name: build2
        run: echo "KEY1=${{secrets.SC_KEY_1}}" >> .env
      - name: build3
        run: echo "KEY2=${{secrets.SC_KEY_2}}" >> .env
      - name: build4
        run: ls
      - name: build5
        run: cat .env
      - name: To File all
        run: echo "${{ secrets.ENV_ALL }}" >> .env_all
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    # setup them
    environment: production
    steps:
      - name: publish
        run: echo 'publishing'
