on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
env:
  test_env: OkOKTestEnv
  super_duper_var: totally_awesome
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.envPAT }}
        configuration-path: ${{ inputs.config-path }}
    - name: step_reusable_workflow_job
      run: echo "testKey=value" >> $GITHUB_OUTPUT

    - name: step 
      run: echo 'YOLOFCC'
    outputs:
        testKey: ${{steps.step_reusable_workflow_job.outputs.testKey}}
