name: Call a reusable workflow and use its outputs

on:
  push:
    branches:
      - main

jobs:
  job1:
    uses: hocptit/test-git-action/.github/workflows/reusable_workflow_job.yaml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: ls

      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
